import { z } from "zod";
import data from "../../../../content/customer-portal.json";
const text = z.string().trim().min(1).max(1000);
export const customerPortalContent = z
  .object({
    profile: text,
    addresses: text,
    favorites: text,
    settings: text,
    support: text,
    home: text,
    save: text,
    saved: text,
    added: text,
    send: text,
    sent: text,
    pending: text,
    edit: text,
    remove: text,
    default: text,
    setDefault: text,
    addAddress: text,
    addressNote: text,
    copyAddress: text,
    copied: text,
    copyFailed: text,
    name: text,
    phone: text,
    email: text,
    profileNote: text,
    emailNote: text,
    label: text,
    postalCode: text,
    prefecture: text,
    city: text,
    line1: text,
    line2: text,
    recipientName: text,
    emptyAddresses: text,
    emptyFavorites: text,
    browse: text,
    favoriteNote: text,
    addFavorite: text,
    unavailableProduct: text,
    openProduct: text,
    marketing: text,
    marketingNote: text,
    security: text,
    google: text,
    revoke: text,
    revokeNote: text,
    export: text,
    exportNote: text,
    close: text,
    closeConfirm: text,
    closeNote: text,
    closeDone: text,
    requests: text,
    requestNote: text,
    kind: text,
    order: text,
    noOrder: text,
    message: text,
    messageHint: text,
    reply: text,
    emptyRequests: text,
    confirmation: text,
    orderHelp: text, deliveryDate: text, changeOpen: text, changeClosed: text, changeShipped: text,
    print: text,
    printNote: text,
    reorder: text,
    reorderNote: text,
    shipping: text,
    tracking: text,
    shippedAt: text,
    deliveredAt: text,
    refunds: text,
    refundNote: text,
    optional: text,
    unavailable: text,
    retry: text,
    invalid: text,
    expired: text,
    conflict: text,
    limit: text,
    "not-found": text,
    login: text,
    refreshNote: text,
    deleteConfirm: text,
    savedRecipients: text,
    selectRecipient: text,
    addressUsage: text,
    requestQueue: text,
    requestQueueNote: text,
    noRequests: text,
    replySave: text,
    requestClose: text,
    privacyQueue: text,
    privacyQueueNote: text,
    sample: text,
    kinds: z
      .object({
        ORDER: text,
        CANCELLATION: text,
        RETURN: text,
        DELIVERY: text,
        OTHER: text,
      })
      .strict(),
    statuses: z.object({ OPEN: text, REPLIED: text, CLOSED: text }).strict(),
    refundStatuses: z
      .object({
        REQUESTED: text,
        PROCESSING: text,
        SUCCEEDED: text,
        FAILED: text,
        CANCELLED: text,
      })
      .strict(),
  })
  .strict()
  .parse(data);
