import { z } from "zod";
import data from "../../../../content/native-fulfillment.json";
import { NATIVE_FULFILLMENT_ACTIONS, NATIVE_CARRIER_CODES, NATIVE_FULFILLMENT_ERROR_CODES, FULFILLMENT_STATUSES } from "@/modules/fulfillment/public";
const text = z.string().trim().min(1);
export const nativeFulfillmentContent = z.object({
  title: text,
  lead: text,
  empty: text,
  all: text,
  filter: text,
  next: text,
  first: text,
  detail: text,
  back: text,
  date: text,
  status: text,
  payment: text,
  order: text,
  items: text,
  destination: text,
  destinationMissing: text,
  privacy: text,
  history: text,
  noHistory: text,
  action: text,
  carrier: text,
  tracking: text,
  trackingHint: text,
  reason: text,
  save: text,
  saving: text,
  reload: text,
  confirm: text,
  warning: text,
  shipment: text,
  shippedAt: text,
  deliveredAt: text,
  notRecorded: text,
  operator: text,
  version: text,
  actions: z.record(z.enum(NATIVE_FULFILLMENT_ACTIONS), text),
  statuses: z.record(z.enum(FULFILLMENT_STATUSES), text),
  carriers: z.record(z.enum(NATIVE_CARRIER_CODES), text),
  reasons: z.record(z.enum(["PAYMENT_REVIEW", "ADDRESS_REVIEW", "STOCK_SHORTAGE", "CUSTOMER_REQUEST", "PAYMENT_ISSUE", "UNDELIVERABLE_ADDRESS", "OTHER"]), text),
  messages: z.record(z.enum(["IDLE", "SAVED", ...NATIVE_FULFILLMENT_ERROR_CODES]), z.string()),
}).strict().parse(data);
