import { z } from "zod";
import source from "../../../../content/operations-console.json";
const text = z.string().trim().min(1).max(600);
export const operationsConsoleContent = z
  .object({
    title: text,
    lead: text,
    brand: text,
    navigation: text,
    menu: text,
    store: text,
    signOut: text,
    refresh: text,
    overview: text,
    orders: text,
    customers: text,
    catalog: text,
    reports: text,
    settings: text,
    search: text,
    reset: text,
    all: text,
    next: text,
    first: text,
    period: text,
    days: text,
    todayIncluded: text,
    orderCount: text,
    orderValue: text,
    captured: text,
    awaiting: text,
    refunds: text,
    cancelled: text,
    unit: text,
    valueNote: text,
    queueNote: text,
    daily: text,
    recent: text,
    viewAll: text,
    quick: text,
    catalogNote: text,
    customersNote: text,
    ordersNote: text,
    settingsNote: text,
    empty: text,
    emptyNote: text,
    unbound: text,
    unboundNote: text,
    denied: text,
    deniedNote: text,
    unavailable: text,
    unavailableNote: text,
    invalid: text,
    invalidNote: text,
    loading: text,
    error: text,
    retry: text,
    reference: text,
    referenceHint: text,
    orderStatus: text,
    payment: text,
    fulfillment: text,
    orderedAt: text,
    total: text,
    customerHistory: text,
    guest: text,
    unknown: text,
    shippingTitle: text,
    shippingNote: text,
    settingsLead: text,
    identity: text,
    verified: text,
    bound: text,
    registration: text,
    registrationNote: text,
    connections: text,
    configured: text,
    notConfigured: text,
    invalidConfig: text,
    configuredNote: text,
    preview: text,
    production: text,
    salesPaused: text,
    salesEnabled: text,
    salesNote: text,
    security: text,
    securityNote: text,
    retentionNote: text,
    marketing: text,
    marketingNote: text,
    adsEnabled: text,
    adsDisabled: text,
    support: text,
    returns: text,
    privacy: text,
    loyalty: text,
    loyaltyNote: text,
    previewDemo: text,
    previewDemoNote: text,
    updated: text,
    date: text,
    attention: text,
    latest: text,
    chartPeak: text,
    connectionNames: z
      .object({ catalog: text, support: text, fulfillment: text })
      .strict(),
    navigationItems: z
      .array(
        z
          .object({
            href: z.enum([
              "/operations",
              "/operations/orders",
              "/operations/native-fulfillments",
              "/operations/customers",
              "/operations/catalog",
              "/operations/reports",
              "/operations/settings",
            ]),
            key: z.enum([
              "fulfillment",
              "overview",
              "orders",
              "customers",
              "catalog",
              "reports",
              "settings",
            ]),
            icon: z.enum([
              "overview",
              "orders",
              "customers",
              "catalog",
              "truck",
              "reports",
              "settings",
            ]),
          })
          .strict(),
      )
      .length(7),
  })
  .strict()
  .parse(source);
